# Docker Compose for RAG API with Qdrant
version: "3.8"

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
